### ISSUE TITLE
Resolver still type checks even when both globalLayer and local layer are not provided

### ISSUE THREAD

**Issue by vecerek** [iamchanii/pothos-plugin-effect#7]
See the following PR demonstrating the issue: https://github.com/iamchanii/pothos-plugin-effect/pull/6.

I would expect a compilation error in such a case instead of a runtime error. The runtime error can be difficult to debug, especially in the case of massive layers.

**Comment by iamchanii** [comment]
I just checked out your demo lightly. it is not a bug and it just a part of not implemented of this library. IMO.

https://github.com/iamchanii/pothos-plugin-effect/blob/6057f97df7a5b1314233c366857f13fb26915896/src/types.ts#L140-L144

I think it is caused by above types. is `globalLayer` able to require type based on `Types['EffectGlobalContext']`?

**Comment by vecerek** [comment]
> it is not a bug and it just a part of not implemented of this library

@iamchanii bug or not, I wish it didn't type check.
